Labfiles/01_ElectricStore_begin/ElectricStore/ViewComponents/NavbarMenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ElectricStore.Data;
using Microsoft.AspNetCore.Mvc;

namespace ElectricStore.ViewComponents
{
    public class NavbarMenuViewComponent : ViewComponent
    {
        private StoreContext _context;

        public NavbarMenuViewComponent(StoreContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            var categories = _context.menuCategories.OrderBy(c => c.Name).ToList();
            return View("MenuCategories", categories);
        }
    }
}

Labfiles/01_ElectricStore_begin/ElectricStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/store-style.css" rel="stylesheet" />
    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/node_modules/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark navbar-custom p-1">
        <a class="navbar-brand" href="@Url.Action("Index", "Products")">Electric Store</a>
        <div class="collapse navbar-collapse" id="nav-content">
            <ul class="navbar-nav" id="nav-content">
                <cache vary-by-route="RefreshCache">
                    @await Component.InvokeAsync("NavbarMenu")
                </cache>
            </ul>
        </div>
    </nav>
    <div class="main-title">
        <h1>Welcome to our Electric Store</h1>
    </div>
    <div>
        @RenderBody()
    </div>
    @RenderSection("Scripts", false)
</body>
</html>